---
- hosts: all
  vars:
    res_dir: ../../res
    redis_server_path: /usr/bin/redis-server
    redis_cli_path: /usr/bin/redis-cli
  tasks:
    - name: Install OpenVZ YUM repo.
      template:
        src={{ res_dir }}/repofiles/openvz.repo.j2
        dest=/etc/yum.repos.d/openvz.repo

    - name: Install OpenVZ kernel
      yum:
        name=vzkernel
        state=latest

    - name: Install vzctl
      yum:
        name=vzctl
        state=latest

    - name: Install vzquota
      yum:
        name=vzquota
        state=latest

    - name: Install ploop
      yum:
        name=ploop
        state=latest

    - name: Reboot
      command: /sbin/shutdown -r now

    - name: Wait for host down
      pause: seconds=10

    - name: Wait for host up
      local_action: wait_for host=10.189.0.2 port=22
      sudo: false

    - name: Remove old kernel
      yum:
        name=kernel
        state=absent
      ignore_errors: true

    - name: Add 10gen repository.
      template:
        dest=/etc/yum.repos.d/mongodb.repo
        src={{ res_dir }}/repofiles/mongodb.repo.j2
        owner=root
        group=root
        mode=644

    - name: Install latest MongoDB Server
      yum:
        name=mongo-10gen-server
        state=latest
      notify: Restart MongoDB

    - name: Install latest MongoDB Tools
      yum:
        name=mongo-10gen
        state=latest
      notify: Restart MongoDB

    - name: Configure MongoDB
      template:
        dest=/etc/mongodb.conf
        src={{ res_dir }}/configfiles/mongodb.conf.minimal.j2
        owner=root
        group=root
        mode=644
      notify: Restart MongoDB

    - name: Download latest Redis tarball.
      get_url:
        dest=/tmp/redis-2.8.3.tar.gz
        "url=http://download.redis.io/releases/redis-2.8.3.tar.gz"
        owner=root
        group=root
        mode=644
      register: redis_download

    - name: Unpack Redis tarball.
      command: tar -xzf /tmp/redis-2.8.3.tar.gz
        chdir=/tmp/
      when: redis_download.changed

    - name: Making Redis.
      command: make
        chdir=/tmp/redis-2.8.3
      when: redis_download.changed
      notify: Restart Redis

    - name: Installing Redis
      shell: PREFIX=/usr/ make install
        chdir=/tmp/redis-2.8.3
      when: redis_download.changed
      notify: Restart Redis

    - name: Installing Redis init scripts.
      template:
        dest=/etc/init.d/redis
        src={{ res_dir }}/initscripts/redis.j2
        owner=root
        group=root
        mode=755
      notify: Restart Redis

    - name: Configure Redis
      template:
        dest=/etc/redis.conf
        src={{ res_dir }}/configfiles/redis.conf.minimal.j2
        owner=root
        group=root
        mode=644
      notify: Restart Redis

  handlers:
    - name: Restart MongoDB
      service: name=mongod state=restarted

    - name: Restart Redis
      service: name=redis state=restarted
