---
# This playbook ensures that Vagrant can get into this machine. This installs
# a backdoor into the system so make sure to only use this role on public
# vagrant boxes.

- name: Add vagrant user
  user: name=vagrant state=present

- name: Add insecure vagrant public key
  authorized_key: user=vagrant key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"

- name: Install sudo
  yum: name=sudo state=present

- name: Add vagrant user to sudoers file
  lineinfile:
    dest=/etc/sudoers
    state=present
    "line=vagrant ALL=(ALL) NOPASSWD:ALL"
