---
# This playbook ensures that Vagrant can get into this machine. This installs
# a backdoor into the system so make sure to only use this role on public
# vagrant boxes.

- name: Add vagrant user
  user: name=vagrant state=present

- name: Create vagrant user's `.ssh` directory
  file:
    path=/home/vagrant/.ssh/
    state=directory
    owner=vagrant
    group=vagrant
    mode=700

- name: Add insecure vagrant public key
  copy:
    src=authorized_keys
    dest=/home/vagrant/.ssh/authorized_keys
    owner=vagrant
    group=vagrant
    mode=600

- name: Install sudo
  yum: name=sudo state=present

- name: Add vagrant user to sudoers file
  lineinfile:
    dest=/etc/sudoers
    state=present
    "line={{ item }}"
    insertafter=EOF
    validate="visudo -cf %s"
  with_items:
    - "vagrant ALL=(ALL) NOPASSWD:ALL"
    - "Defaults:vagrant !requiretty"
